Updates the modules headers and options to work with the latest version of stubbs and completes the deploy workflow to the point of creating and kicking off the build jobs.

diff --git a/commands/install/script b/commands/install/script
--- a/commands/install/script
+++ b/commands/install/script
@@ -1,44 +1,76 @@
 #!/usr/bin/env bash
-#
-#/ command: third-party-packages:install: "Install and start the Jenkins instance"
-#
-#/ usage: rerun third-party-packages:install 
-#
-#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: 
 
-# Read module function library.
-. $RERUN_MODULE_DIR/lib/functions.sh || { 
+# To implement this command, edit the "Command implementation" section below. 
+
+# Usage
+# -----
+
+# Comments prefixed with `#/` are managed by stubbs.
+# The `command` and `usage` comments describe the command
+# and show its options.
+# 
+#/ command: third-party-packages:install: "Install and start the Jenkins instance"
+#/ usage: rerun third-party-packages:install 
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions, too.
+. $RERUN_MODULE_DIR/lib/functions.sh install || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
 # Error handling
 # ---------------
-# * Trap calls `rerun_die` with standard message.
-# * Exit upon command errors or accessing unset variables.
-#   * See [set](http://ss64.com/bash/set.html)
-trap 'rerun_die "*** command failed: third-party-packages:install. ***"' ERR
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: third-party-packages:install. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
 set -o nounset -o pipefail
 
-# Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/install/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/install/options.sh || rerun_die "Failed loading options parser."
-    rerun_options_parse "$@"
-}
+# Command variables
+# -----------------
+
+# This command script can access the following variables
+# declared by `rerun` or by the option parser function.
+
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: 
+
+# The `rerun_options_parse` function processes the command line
+# arguments. Each accepted command line flag results in setting 
+# one the corresponding option variables.
+
+rerun_options_parse "$@"
 
 
-# ------------------------------
-# Your implementation goes here.
-# ------------------------------
+# Command implementation
+# ----------------------
+
+# - - -
+# Put the command implementation here.
+# - - -
 
 # Bootstrap required rerun modules:
-sudo yum --quiet -q -y install rerun-jenkins
-sudo yum --quiet -q -y install rerun-rpm
+sudo yum --quiet -y install rerun-jenkins
+sudo yum --quiet -y install rerun-rpm
 
 # Bootstrap required packages:
-sudo yum --quiet -q -y install rpm-build
-sudo yum --quiet -q -y install java-devel-openjdk
-sudo yum --quiet -q -y install xmlstarlet
+sudo yum --quiet -y install rpm-build
+sudo yum --quiet -y install java-devel-openjdk
+sudo yum --quiet -y install xmlstarlet
 
 # Bootstrap Jenkins installation:
 rerun jenkins:install
